<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCcixKNr\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCcixKNr/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCcixKNr.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCcixKNr\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCcixKNr\App_KernelDevDebugContainer([
    'container.build_hash' => 'CcixKNr',
    'container.build_id' => 'b6fd5e9a',
    'container.build_time' => 1723655489,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCcixKNr');
