<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGGFsd9a\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGGFsd9a/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGGFsd9a.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGGFsd9a\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGGFsd9a\App_KernelDevDebugContainer([
    'container.build_hash' => 'GGFsd9a',
    'container.build_id' => '80cdb2da',
    'container.build_time' => 1722692337,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGGFsd9a');
